"""
Stage 1 - Incubation Phase
Customer Success FTE - Core Prototype
Handles queries from Email, WhatsApp, and Web Form channels
"""

import os
import json
from typing import Optional
from enum import Enum
from anthropic import Anthropic

# Initialize client - using Claude as the AI model
client = Anthropic()

# ─────────────────────────────────────────────
# Load context files
# ─────────────────────────────────────────────

CONTEXT_DIR = os.path.join(os.path.dirname(__file__), "../../context")

def load_context_file(filename: str) -> str:
    filepath = os.path.join(CONTEXT_DIR, filename)
    with open(filepath, "r", encoding="utf-8") as f:
        return f.read()

PRODUCT_DOCS = load_context_file("product-docs.md")
COMPANY_PROFILE = load_context_file("company-profile.md")
ESCALATION_RULES = load_context_file("escalation-rules.md")
BRAND_VOICE = load_context_file("brand-voice.md")


# ─────────────────────────────────────────────
# Channel Enum
# ─────────────────────────────────────────────

class Channel(str, Enum):
    EMAIL = "email"
    WHATSAPP = "whatsapp"
    WEB_FORM = "web_form"


# ─────────────────────────────────────────────
# In-memory state (prototype only)
# ─────────────────────────────────────────────

conversation_history = {}   # conversation_id -> list of messages
ticket_store = {}           # ticket_id -> dict
customer_store = {}         # email/phone -> customer_id


# ─────────────────────────────────────────────
# System Prompt
# ─────────────────────────────────────────────

SYSTEM_PROMPT = f"""You are a Customer Success AI Agent for TechNova SaaS platform.
You work 24/7 handling customer support queries across three channels: Email, WhatsApp, and Web Form.

## Company & Product Knowledge
{COMPANY_PROFILE}

## Product Documentation
{PRODUCT_DOCS}

## Escalation Rules
{ESCALATION_RULES}

## Brand Voice & Communication Style
{BRAND_VOICE}

## Your Workflow (ALWAYS follow this order)
1. Identify the customer and their channel
2. Check if this is a follow-up or new issue
3. Analyze the customer's message and sentiment
4. Search your knowledge (product docs above) for relevant information
5. Decide: resolve OR escalate
6. Format response appropriately for the channel
7. If escalating, clearly state the reason

## Hard Constraints
- NEVER discuss competitor products
- NEVER promise features not in the documentation
- NEVER process refunds - always escalate to billing team
- NEVER share internal processes
- ALWAYS adapt response style to the channel

## Response Format
Always respond in this JSON format:
{{
    "action": "resolve" | "escalate" | "ask_clarification",
    "response": "your response to the customer",
    "escalation_reason": "reason if escalating, else null",
    "escalation_team": "billing | legal | engineering | sales | senior_support | null",
    "sentiment": "positive" | "neutral" | "negative",
    "sentiment_score": 0.0 to 1.0 (0=very negative, 1=very positive),
    "topics": ["list", "of", "topics"],
    "resolution_status": "resolved" | "pending" | "escalated"
}}
"""


# ─────────────────────────────────────────────
# Channel-aware response formatting
# ─────────────────────────────────────────────

def format_response_for_channel(response: str, channel: Channel, ticket_id: str) -> str:
    if channel == Channel.EMAIL:
        return f"""{response}

---
Ticket Reference: {ticket_id}
TechNova Support Team | support@technova.io
This response was generated by our AI assistant. Reply to request human support."""

    elif channel == Channel.WHATSAPP:
        # Keep it short for WhatsApp
        if len(response) > 300:
            response = response[:297] + "..."
        return f"{response}\n\nTicket: {ticket_id} | Type 'human' for live support 💬"

    else:  # web_form
        return f"""{response}

---
Ticket ID: {ticket_id}
Need more help? Reply to this message or visit support.technova.io"""


# ─────────────────────────────────────────────
# Core Agent Function
# ─────────────────────────────────────────────

def process_customer_message(
    message: str,
    channel: str,
    customer_identifier: str,  # email or phone
    customer_name: str = "Customer",
    conversation_id: Optional[str] = None,
    subject: Optional[str] = None,
) -> dict:
    """
    Main function to process a customer message through the AI agent.

    Args:
        message: The customer's message text
        channel: 'email', 'whatsapp', or 'web_form'
        customer_identifier: email address or phone number
        customer_name: customer's name
        conversation_id: existing conversation ID for follow-ups
        subject: email subject or form subject

    Returns:
        dict with response, action, ticket_id, etc.
    """

    # Normalize channel
    try:
        ch = Channel(channel)
    except ValueError:
        ch = Channel.WEB_FORM

    # Generate IDs
    import uuid
    ticket_id = f"TKT-{str(uuid.uuid4())[:8].upper()}"
    if not conversation_id:
        conversation_id = f"CONV-{str(uuid.uuid4())[:8].upper()}"

    # Store ticket
    ticket_store[ticket_id] = {
        "ticket_id": ticket_id,
        "conversation_id": conversation_id,
        "customer": customer_identifier,
        "customer_name": customer_name,
        "channel": ch.value,
        "subject": subject or "Support Request",
        "message": message,
        "status": "open"
    }

    # Build conversation history
    if conversation_id not in conversation_history:
        conversation_history[conversation_id] = []

    # Add current message to history
    conversation_history[conversation_id].append({
        "role": "user",
        "content": f"[Channel: {ch.value}] [Customer: {customer_name} ({customer_identifier})] [Subject: {subject or 'N/A'}]\n\nMessage: {message}"
    })

    # Call Claude API
    response = client.messages.create(
        model="claude-opus-4-6",
        max_tokens=1024,
        system=SYSTEM_PROMPT,
        messages=conversation_history[conversation_id]
    )

    raw_output = response.content[0].text

    # Parse JSON response
    try:
        # Extract JSON from response
        import re
        json_match = re.search(r'\{[\s\S]*\}', raw_output)
        if json_match:
            agent_response = json.loads(json_match.group())
        else:
            agent_response = {
                "action": "resolve",
                "response": raw_output,
                "escalation_reason": None,
                "escalation_team": None,
                "sentiment": "neutral",
                "sentiment_score": 0.5,
                "topics": [],
                "resolution_status": "pending"
            }
    except json.JSONDecodeError:
        agent_response = {
            "action": "resolve",
            "response": raw_output,
            "escalation_reason": None,
            "escalation_team": None,
            "sentiment": "neutral",
            "sentiment_score": 0.5,
            "topics": [],
            "resolution_status": "pending"
        }

    # Format response for channel
    customer_facing_response = format_response_for_channel(
        agent_response["response"], ch, ticket_id
    )

    # Add agent response to history
    conversation_history[conversation_id].append({
        "role": "assistant",
        "content": raw_output
    })

    # Update ticket status
    ticket_store[ticket_id]["status"] = agent_response.get("resolution_status", "pending")
    ticket_store[ticket_id]["escalation_reason"] = agent_response.get("escalation_reason")
    ticket_store[ticket_id]["escalation_team"] = agent_response.get("escalation_team")

    return {
        "ticket_id": ticket_id,
        "conversation_id": conversation_id,
        "channel": ch.value,
        "action": agent_response.get("action", "resolve"),
        "response": customer_facing_response,
        "raw_response": agent_response.get("response", ""),
        "escalation_reason": agent_response.get("escalation_reason"),
        "escalation_team": agent_response.get("escalation_team"),
        "sentiment": agent_response.get("sentiment", "neutral"),
        "sentiment_score": agent_response.get("sentiment_score", 0.5),
        "topics": agent_response.get("topics", []),
        "resolution_status": agent_response.get("resolution_status", "pending")
    }


def get_ticket(ticket_id: str) -> Optional[dict]:
    return ticket_store.get(ticket_id)


def get_conversation_history(conversation_id: str) -> list:
    return conversation_history.get(conversation_id, [])


# ─────────────────────────────────────────────
# CLI Demo
# ─────────────────────────────────────────────

if __name__ == "__main__":
    print("=" * 60)
    print("TechNova Customer Success FTE - Prototype Demo")
    print("=" * 60)

    # Test Case 1: Email - Password Reset
    print("\n[TEST 1] Email - Password Reset")
    result = process_customer_message(
        message="Hi, I've been trying to reset my password for the past hour but I'm not receiving the reset email. I've checked my spam folder multiple times.",
        channel="email",
        customer_identifier="alice@company.com",
        customer_name="Alice Johnson",
        subject="Cannot reset my password"
    )
    print(f"Action: {result['action']}")
    print(f"Ticket: {result['ticket_id']}")
    print(f"Sentiment: {result['sentiment']} ({result['sentiment_score']})")
    print(f"Response:\n{result['response']}\n")

    # Test Case 2: WhatsApp - Short message
    print("\n[TEST 2] WhatsApp - Short message")
    result2 = process_customer_message(
        message="forgot password",
        channel="whatsapp",
        customer_identifier="+14155550001",
        customer_name="Bob Smith"
    )
    print(f"Action: {result2['action']}")
    print(f"Ticket: {result2['ticket_id']}")
    print(f"Response:\n{result2['response']}\n")

    # Test Case 3: Escalation - Pricing
    print("\n[TEST 3] Email - Pricing (should escalate)")
    result3 = process_customer_message(
        message="Can you tell me about enterprise pricing? We have 500 users and need custom SLA.",
        channel="email",
        customer_identifier="cto@bigcorp.com",
        customer_name="David Chen",
        subject="Enterprise pricing inquiry"
    )
    print(f"Action: {result3['action']}")
    print(f"Escalation Reason: {result3['escalation_reason']}")
    print(f"Escalation Team: {result3['escalation_team']}")
    print(f"Response:\n{result3['response']}\n")
